<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="0.152" timestamp="2023-09-24T22:16:43.370421" hostname="Zorans-MacBook-Pro.local"><testcase classname="test_multiplication" name="test_multiplication_11[1-11]" time="0.003" /><testcase classname="test_multiplication" name="test_multiplication_11[2-22]" time="0.004" /><testcase classname="test_multiplication" name="test_multiplication_11[3-35]" time="0.003"><failure message="assert (11 * 3) == 35">num = 3, output = 35

    @pytest.mark.specialTest
    @pytest.mark.parametrize("num, output", [(1, 11), (2, 22), (3, 35), (4, 44)])
    def test_multiplication_11(num, output):
&gt;       assert 11 * num == output
E       assert (11 * 3) == 35

test_multiplication.py:6: AssertionError</failure></testcase><testcase classname="test_multiplication" name="test_multiplication_11[4-44]" time="0.001" /></testsuite></testsuites>